/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
    interface CranjisMcbasketball {
        "name": string;
    }
    interface FatherJohnMisterT {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCranjisMcbasketballElement extends Components.CranjisMcbasketball, HTMLStencilElement {
    }
    var HTMLCranjisMcbasketballElement: {
        prototype: HTMLCranjisMcbasketballElement;
        new (): HTMLCranjisMcbasketballElement;
    };
    interface HTMLFatherJohnMisterTElement extends Components.FatherJohnMisterT, HTMLStencilElement {
    }
    var HTMLFatherJohnMisterTElement: {
        prototype: HTMLFatherJohnMisterTElement;
        new (): HTMLFatherJohnMisterTElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "cranjis-mcbasketball": HTMLCranjisMcbasketballElement;
        "father-john-mister-t": HTMLFatherJohnMisterTElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface CranjisMcbasketball {
        "name"?: string;
    }
    interface FatherJohnMisterT {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "cranjis-mcbasketball": CranjisMcbasketball;
        "father-john-mister-t": FatherJohnMisterT;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "cranjis-mcbasketball": LocalJSX.CranjisMcbasketball & JSXBase.HTMLAttributes<HTMLCranjisMcbasketballElement>;
            "father-john-mister-t": LocalJSX.FatherJohnMisterT & JSXBase.HTMLAttributes<HTMLFatherJohnMisterTElement>;
        }
    }
}
